# Generated by Django 4.1.7 on 2023-03-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('op1', models.CharField(blank=True, max_length=200, null=True)),
                ('op2', models.CharField(blank=True, max_length=200, null=True)),
                ('op3', models.CharField(blank=True, max_length=200, null=True)),
                ('op4', models.CharField(blank=True, max_length=200, null=True)),
                ('ans', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
