# Generated by Django 4.1.7 on 2023-03-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_category_quizmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='quiz.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='quiz.category'),
            preserve_default=False,
        ),
    ]
