# Generated by Django 4.1.7 on 2023-03-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_category_description_name_category_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='image',
        ),
    ]
