# Generated by Django 4.1.7 on 2023-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quizmodel_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(blank=True, max_length=100, null=True)),
                ('theme_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
