# Generated by Django 4.1.7 on 2023-03-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='quiz.theme'),
        ),
    ]
